public class Test {
    public static void main(String[] args) throws  InterruptedException{
        WeatherStation s = new WeatherStation();
        WeatherStation s1 = new WeatherStation();
        WeatherStation s2 = new WeatherStation();
        MeteorologicalCenter.getInstance().attachWeatherStation(s);
        MeteorologicalCenter.getInstance().attachWeatherStation(s1);
        MeteorologicalCenter.getInstance().attachWeatherStation(s2);
        Anemometer a = new Anemometer();
        s.attachAnemometer(a);
        Anemometer a1 = new Anemometer();
        s1.attachAnemometer(a1);
        Anemometer a2 = new Anemometer();
        s2.attachAnemometer(a2);
        Barometer b = new Barometer();
        s.attachBarometer(b);
        Barometer b1 = new Barometer();
        s1.attachBarometer(b1);
        Barometer b2 = new Barometer();
        s2.attachBarometer(b2);
        Hygrometer h = new Hygrometer();
        s.attachHygrometer(h);
        Hygrometer h1 = new Hygrometer();
        s1.attachHygrometer(h1);
        Hygrometer h2 = new Hygrometer();
        s2.attachHygrometer(h2);
        RainGauge r = new RainGauge();
        s.attachRainGauge(r);
        RainGauge r1 = new RainGauge();
        s1.attachRainGauge(r1);
        RainGauge r2 = new RainGauge();
        s2.attachRainGauge(r2);
        Thermometer t = new Thermometer();
        s.attachThermometer(t);Thermometer t1 = new Thermometer();
        s1.attachThermometer(t1);
        Thermometer t2 = new Thermometer();
        s2.attachThermometer(t2);
        WindVane w = new WindVane();
        s.attachWindVane(w);
        WindVane w1 = new WindVane();
        s1.attachWindVane(w1);
        WindVane w2 = new WindVane();
        s2.attachWindVane(w2);
        Thread.sleep(15000);
        s.stopStation();
        s1.stopStation();
        s2.stopStation();
        a.interrupt();
        b.interrupt();
        h.interrupt();
        r.interrupt();
        t.interrupt();
        w.interrupt();
        a1.interrupt();
        b1.interrupt();
        h1.interrupt();
        r1.interrupt();
        t1.interrupt();
        w1.interrupt();
        a2.interrupt();
        b2.interrupt();
        h2.interrupt();
        r2.interrupt();
        t2.interrupt();
        w2.interrupt();
    }
}
